# Site settings
title: Nicholas Guyett - Professional Web Developer
email: nicholas.guyett@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Nicholas Guyett is a self-taught, full-stack web developer with experience
  using php, ruby, and javascript (client-side and serverside).  He is available
  for hire or for freelancing.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.nicholasguyett.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
